# Generated by Django 3.2.9 on 2021-12-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='No description provided', max_length=200),
        ),
    ]
