<win1>
    GridLayout:
        cols:1
        size: root.width,root.height
        GridLayout:
            cols:2
            Label:
                text:"enter your name"
            TextInput:
                hint:"enter your name"
                multiline:False
            Label:
                text:"enter your password"
            TextInput:
                hint:"enter your name"
                multiline:False
                password:True