# Generated by Django 3.2.10 on 2022-01-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='last_update',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_by',
            new_name='posted_by',
        ),
    ]
