# Generated by Django 3.2.10 on 2022-01-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to=None)),
                ('category', models.CharField(choices=[('electronic', 'Electronic'), ('cosmetic', 'Costmetic')], max_length=50)),
            ],
        ),
    ]
